In [6]:
## Numpy Crash couorse
import numpy as np

In [2]:
import sys 
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [8]:
arr = np.array(my_list) 

In [10]:
arr

array([0, 1, 2, 3, 4, 5])

In [11]:
np.arange(15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(3.0) 

array([0., 1., 2.])

In [13]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [17]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [18]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [19]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int64)

In [20]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [21]:
np.arange(10,10) 

array([], dtype=int64)

In [22]:
np.arange()

TypeError: arange() requires stop to be specified.

In [23]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [24]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [25]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [26]:
np.zeros(3) # parameter  tunning 

array([0., 0., 0.])

In [27]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [28]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [29]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [30]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [32]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunnin g

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [34]:
print(np.zeros(n,dtype=int)) ## hypyerparameter tunning 

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [35]:
print(np.zeros(n1))


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [36]:
np.ones(3)

array([1., 1., 1.])

In [37]:
np.ones(4, dtype=int) 

array([1, 1, 1, 1])

In [38]:
np.ones(4)

array([1., 1., 1., 1.])

In [40]:
n

(6, 7)

In [41]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [42]:
np.twos((2,3)) 

AttributeError: module 'numpy' has no attribute 'twos'

In [43]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [44]:
np.ones(2)

array([1., 1.])

In [45]:
np.ones((2,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.ones((6,7),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [47]:
np.two(2,3)

AttributeError: module 'numpy' has no attribute 'two'

In [48]:
range(5)

range(0, 5)

In [49]:
r = range(5)
r

range(0, 5)

In [50]:
for i in r:
    print(i)

0
1
2
3
4


In [51]:
list(range(5))

[0, 1, 2, 3, 4]

In [52]:
range(1,10)

range(1, 10)

In [53]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
y=list(range(1,11))
y

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [55]:
rand(3,2)

NameError: name 'rand' is not defined

In [56]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [57]:
np.random.rand(5)

array([0.55822777, 0.42724056, 0.09535183, 0.84435622, 0.33442303])

In [58]:
np.random.rand(2,4)

array([[3.61067791e-01, 4.77195414e-01, 3.91277256e-04, 9.52316462e-02],
       [2.39915459e-01, 7.75658974e-01, 1.96642554e-01, 1.09124985e-01]])

In [61]:
np.random.randint(2,4)

2

In [62]:
np.random.randint(2,20) # 2nd argument is exlusive

2

In [63]:
np.random.randint(0,1) 

0

In [64]:
np.random.randint(10,20,5)

array([19, 18, 18, 11, 13], dtype=int32)

In [67]:
np.random.randint(1,6,4)

array([2, 2, 4, 5], dtype=int32)

In [66]:
np.random.randint(1)  

0

In [68]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [69]:
np.random.randint(-30,20,10) 

array([  8,   8, -29,  14,  -1,  -7,  17,  12,   2,  14], dtype=int32)

In [70]:
np.random.randint(20,30,10) 

array([28, 27, 29, 25, 24, 23, 23, 21, 21, 23], dtype=int32)

In [71]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

7

In [72]:
np.random.randint(10,21,3)

array([14, 13, 11], dtype=int32)

In [73]:
np.random.randint(1,12,10)

array([10,  5,  6, 11,  4,  2, 11,  1,  9,  1], dtype=int32)

In [74]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 10*10 mtri

array([[20, 13, 10, 10, 24, 19, 24, 23, 36, 30],
       [16, 31, 27, 29, 18, 14, 16, 26, 27, 36],
       [33, 11, 36, 31, 12, 18, 31, 17, 24, 22],
       [25, 33, 38, 29, 19, 19, 25, 30, 34, 20],
       [12, 28, 24, 39, 38, 15, 16, 17, 25, 25],
       [23, 22, 16, 32, 36, 12, 17, 19, 20, 18],
       [21, 30, 31, 13, 31, 36, 11, 34, 27, 35],
       [32, 26, 36, 33, 20, 16, 29, 21, 27, 27],
       [28, 15, 36, 39, 21, 13, 20, 34, 16, 11],
       [24, 36, 20, 10, 11, 34, 25, 30, 21, 32]], dtype=int32)

In [75]:
np.random.randint(1,100,(12,12)) #generre the element 10 -30 with 4*4 mtri

array([[83, 73,  7, 99, 96, 29, 30, 26, 32, 79, 71, 25],
       [71, 95,  7, 34,  1,  6, 67, 63,  9, 89, 50, 33],
       [67, 38, 93, 92, 75, 77, 47, 74, 73, 73, 58,  3],
       [90, 55, 59, 44, 30, 86, 48,  4, 63, 80, 53, 13],
       [24, 42, 31, 62, 59,  1,  5, 51, 66, 75, 40, 80],
       [ 4,  7, 23, 29, 37, 83, 80, 35,  3, 92, 14, 75],
       [20, 38, 64, 38, 79, 10, 24, 99, 67, 13, 35, 98],
       [86, 82, 30, 70, 48, 48, 71, 34, 12, 43, 46, 10],
       [24, 91, 61, 66, 21, 22, 98, 89,  4, 85, 10,  7],
       [30, 74,  5, 67, 29, 93, 37, 95, 30, 91, 18, 38],
       [48, 99,  2, 85, 41, 34, 27, 86, 96, 57, 53, 96],
       [22, 43, 29, 43, 29, 95, 33, 46, 70, 93, 68, 67]], dtype=int32)

In [76]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
b = np.random.randint(10,20,(5,4))
b

array([[17, 15, 19, 18],
       [18, 17, 11, 13],
       [12, 10, 17, 15],
       [11, 18, 19, 15],
       [17, 18, 16, 15]], dtype=int32)

In [78]:
type(b)

numpy.ndarray

In [79]:
b


array([[17, 15, 19, 18],
       [18, 17, 11, 13],
       [12, 10, 17, 15],
       [11, 18, 19, 15],
       [17, 18, 16, 15]], dtype=int32)

In [80]:
b[:] 

array([[17, 15, 19, 18],
       [18, 17, 11, 13],
       [12, 10, 17, 15],
       [11, 18, 19, 15],
       [17, 18, 16, 15]], dtype=int32)

In [81]:
b[1:3]

array([[18, 17, 11, 13],
       [12, 10, 17, 15]], dtype=int32)

In [83]:
b[1,3]

np.int32(13)

In [84]:
b

array([[17, 15, 19, 18],
       [18, 17, 11, 13],
       [12, 10, 17, 15],
       [11, 18, 19, 15],
       [17, 18, 16, 15]], dtype=int32)

In [85]:
b[1,3]

np.int32(13)

In [86]:
b[-4,-2]

np.int32(11)

In [87]:
b[:]

array([[17, 15, 19, 18],
       [18, 17, 11, 13],
       [12, 10, 17, 15],
       [11, 18, 19, 15],
       [17, 18, 16, 15]], dtype=int32)

In [88]:
b[-4,-2]

np.int32(11)

In [89]:
#Operations

In [90]:
a = np.random.randint(10,20,10)
a

array([11, 12, 11, 12, 15, 11, 10, 17, 13, 18], dtype=int32)

In [91]:
id(a)

3041138008176

In [92]:
arr

array([0, 1, 2, 3, 4, 5])

In [94]:
arr2 = np.random.randint(0,100,(10,10))

In [95]:
arr2

array([[46, 61, 58, 86,  2, 52, 90,  2, 37, 38],
       [20, 44, 62,  9,  5,  1, 91,  4, 59, 47],
       [14, 46, 37, 95, 86, 20, 65, 57, 18, 90],
       [63, 91, 88, 75, 11, 27, 93, 91, 85, 60],
       [84, 77, 54,  1, 16, 43, 89, 98, 32, 12],
       [11, 98, 42, 69, 91,  4, 77, 64, 47, 60],
       [ 9, 27, 32, 27, 85, 46, 38, 35, 49, 98],
       [67, 78, 31, 97, 77, 49, 99, 76, 91,  4],
       [28,  7, 29, 29, 54, 76, 52, 87,  3, 94],
       [47, 35, 60, 25, 23, 49, 83, 73, 26, 68]], dtype=int32)

In [96]:
arr

array([0, 1, 2, 3, 4, 5])

In [97]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [98]:
arr[:4] 

array([0, 1, 2, 3])

In [99]:
arr[:4] 

array([0, 1, 2, 3])

In [100]:
arr2[:4]

array([[46, 61, 58, 86,  2, 52, 90,  2, 37, 38],
       [20, 44, 62,  9,  5,  1, 91,  4, 59, 47],
       [14, 46, 37, 95, 86, 20, 65, 57, 18, 90],
       [63, 91, 88, 75, 11, 27, 93, 91, 85, 60]], dtype=int32)

In [101]:
arr2[0:5] 

array([[46, 61, 58, 86,  2, 52, 90,  2, 37, 38],
       [20, 44, 62,  9,  5,  1, 91,  4, 59, 47],
       [14, 46, 37, 95, 86, 20, 65, 57, 18, 90],
       [63, 91, 88, 75, 11, 27, 93, 91, 85, 60],
       [84, 77, 54,  1, 16, 43, 89, 98, 32, 12]], dtype=int32)

In [102]:
arr2

array([[46, 61, 58, 86,  2, 52, 90,  2, 37, 38],
       [20, 44, 62,  9,  5,  1, 91,  4, 59, 47],
       [14, 46, 37, 95, 86, 20, 65, 57, 18, 90],
       [63, 91, 88, 75, 11, 27, 93, 91, 85, 60],
       [84, 77, 54,  1, 16, 43, 89, 98, 32, 12],
       [11, 98, 42, 69, 91,  4, 77, 64, 47, 60],
       [ 9, 27, 32, 27, 85, 46, 38, 35, 49, 98],
       [67, 78, 31, 97, 77, 49, 99, 76, 91,  4],
       [28,  7, 29, 29, 54, 76, 52, 87,  3, 94],
       [47, 35, 60, 25, 23, 49, 83, 73, 26, 68]], dtype=int32)

In [103]:
arr2[1,4]

np.int32(5)

In [104]:
arr2[-5,5] 

np.int32(4)

In [105]:
arr2[-5,-5] 

np.int32(4)

In [106]:
arr2[-1,-2]

np.int32(26)