In [1]:
l = []  
l

[]

In [2]:
len(l) 

0

In [3]:
l1 = [10, 20, 30] 
l1

[10, 20, 30]

In [4]:
len(l1)

3

In [5]:
l1

[10, 20, 30]

In [6]:
l1.append(40)
l1.append(50)
l1.append(60)
l1.append(10)

In [7]:
l1

[10, 20, 30, 40, 50, 60, 10]

In [8]:
len(l1)

7

In [9]:
l1.append(70, 80) 

TypeError: list.append() takes exactly one argument (2 given)

In [10]:
l1

[10, 20, 30, 40, 50, 60, 10]

In [11]:
l1.append(['a', 'b', 'c'])

In [12]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [13]:
l2 = [34, 5.3, 'prakash', 1+2j, True] 
l2

[34, 5.3, 'prakash', (1+2j), True]

In [14]:
print(l)
print(l1)
print(l2)

[]
[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]
[34, 5.3, 'prakash', (1+2j), True]


In [15]:
print(len(l))
print(len(l1))
print(len(l2))

0
8
5


In [16]:
print(id(l))
print(id(l1))
print(id(l2))

2439211059584
2439211059776
2439233893952


In [17]:
print(type(l))
print(type(l1))
print(type(l2))

<class 'list'>
<class 'list'>
<class 'list'>


In [18]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [19]:
# list membership 

10 in l1

True

In [20]:
['a', 'b', 'c'] in l1

True

In [21]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [22]:
100 in l1

False

In [23]:
l2

[34, 5.3, 'prakash', (1+2j), True]

In [24]:
l3 = l2.copy() 

In [25]:
l3

[34, 5.3, 'prakash', (1+2j), True]

In [26]:
print(id(l2))
print(id(l3))

2439233893952
2439233549184


In [27]:
print(l)
print(l1)
print(l2)
print(l3)

[]
[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]
[34, 5.3, 'prakash', (1+2j), True]
[34, 5.3, 'prakash', (1+2j), True]


In [28]:
l3

[34, 5.3, 'prakash', (1+2j), True]

In [29]:
len(l3)

5

In [30]:
l3.clear() 

In [31]:
l3

[]

In [32]:
len(l3)

0

In [33]:
del l3

In [34]:
print(l)
print(l1)
print(l2)

[]
[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]
[34, 5.3, 'prakash', (1+2j), True]


In [35]:
l2.count(5.3)

1

In [36]:
l1.count(10) 

2

In [37]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [38]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [39]:
l1[:] 

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [40]:
l1[-1] 

['a', 'b', 'c']

In [41]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [42]:
l1[100] 

IndexError: list index out of range

In [43]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [44]:
l1[4:] 

[50, 60, 10, ['a', 'b', 'c']]

In [45]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [46]:
l1[3:-1] 

[40, 50, 60, 10]

In [47]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [48]:
l1[0:10:3] 

[10, 40, 10]

In [49]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [50]:
l1[::1] 

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [51]:
l1[::2]  

[10, 30, 50, 10]

In [52]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [53]:
l1[::3] 

[10, 40, 10]

In [54]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [55]:
l1.count(10)

2

In [56]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [57]:
l1[::-1] 

[['a', 'b', 'c'], 10, 60, 50, 40, 30, 20, 10]

In [58]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [59]:
l1[::-2]

[['a', 'b', 'c'], 60, 40, 20]

In [60]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [61]:
l1[::-3] 

[['a', 'b', 'c'], 50, 20]

In [62]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [63]:
l1[4:-3] 

[50]

In [64]:
print(l)
print(l1)
print(l2)

[]
[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]
[34, 5.3, 'prakash', (1+2j), True]


In [65]:
l1

[10, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [66]:
l1[0] 

10

In [67]:
l1[0] = 100 

In [68]:
l1

[100, 20, 30, 40, 50, 60, 10, ['a', 'b', 'c']]

In [69]:
l1[-1] = 'prakash senapati'
l1

[100, 20, 30, 40, 50, 60, 10, 'prakash senapati']

In [70]:
l1

[100, 20, 30, 40, 50, 60, 10, 'prakash senapati']

In [71]:
print(l)
print(l1)
print(l2)

[]
[100, 20, 30, 40, 50, 60, 10, 'prakash senapati']
[34, 5.3, 'prakash', (1+2j), True]


In [72]:
l.extend(l2) 

In [73]:
print(l)
print(l1)
print(l2)

[34, 5.3, 'prakash', (1+2j), True]
[100, 20, 30, 40, 50, 60, 10, 'prakash senapati']
[34, 5.3, 'prakash', (1+2j), True]


In [74]:
l.extend(l1) 
l

[34,
 5.3,
 'prakash',
 (1+2j),
 True,
 100,
 20,
 30,
 40,
 50,
 60,
 10,
 'prakash senapati']

In [75]:
l.index('prakash') 

2

In [76]:
l1

[100, 20, 30, 40, 50, 60, 10, 'prakash senapati']

In [77]:
l1.append(10)

In [78]:
l1

[100, 20, 30, 40, 50, 60, 10, 'prakash senapati', 10]

In [79]:
l1.index(10) 

6

In [80]:
l1

[100, 20, 30, 40, 50, 60, 10, 'prakash senapati', 10]

In [81]:
l1.insert(2, 25) 

In [82]:
l1

[100, 20, 25, 30, 40, 50, 60, 10, 'prakash senapati', 10]

In [83]:
l1.pop()

10

In [84]:
l1

[100, 20, 25, 30, 40, 50, 60, 10, 'prakash senapati']

In [85]:
l1.pop()

'prakash senapati'

In [86]:
l1

[100, 20, 25, 30, 40, 50, 60, 10]

In [87]:
l

[34,
 5.3,
 'prakash',
 (1+2j),
 True,
 100,
 20,
 30,
 40,
 50,
 60,
 10,
 'prakash senapati']

In [88]:
l.pop()

'prakash senapati'

In [89]:
l.pop()

10

In [90]:
l

[34, 5.3, 'prakash', (1+2j), True, 100, 20, 30, 40, 50, 60]

In [91]:
l.pop(2)

'prakash'

In [92]:
l

[34, 5.3, (1+2j), True, 100, 20, 30, 40, 50, 60]

In [93]:
l[3]

True

In [94]:
l

[34, 5.3, (1+2j), True, 100, 20, 30, 40, 50, 60]

In [95]:
l.remove(1+2j)

In [96]:
l

[34, 5.3, True, 100, 20, 30, 40, 50, 60]

In [97]:
l.reverse()

In [98]:
l

[60, 50, 40, 30, 20, 100, True, 5.3, 34]

In [101]:
l.reverse()

In [102]:
l

[34, 5.3, True, 100, 20, 30, 40, 50, 60]

In [103]:
print(l)
print(l1)
print(l2)

[34, 5.3, True, 100, 20, 30, 40, 50, 60]
[100, 20, 25, 30, 40, 50, 60, 10]
[34, 5.3, 'prakash', (1+2j), True]


In [107]:
l2.sort()

TypeError: '<' not supported between instances of 'str' and 'float'

In [106]:
l

[True, 5.3, 20, 30, 34, 40, 50, 60, 100]

In [108]:
l1

[100, 20, 25, 30, 40, 50, 60, 10]

In [109]:
l1.sort()

In [110]:
l1

[10, 20, 25, 30, 40, 50, 60, 100]

In [111]:
l1.sort(reverse= True)
l1

[100, 60, 50, 40, 30, 25, 20, 10]

In [112]:
l2

[34, 5.3, 'prakash', (1+2j), True]

In [113]:
l3 = [3 , 1, 2 ]
l3

[3, 1, 2]

In [114]:
l3.sort() # paramteter tunning 
l3

[1, 2, 3]

In [115]:
l3.sort(reverse=True)
l3

[3, 2, 1]

In [116]:
l1

[100, 60, 50, 40, 30, 25, 20, 10]

In [117]:
l2

[34, 5.3, 'prakash', (1+2j), True]

In [118]:
l2[2]

'prakash'

In [119]:
l2

[34, 5.3, 'prakash', (1+2j), True]

In [120]:
l2[2][0] 

'p'

In [124]:
print(l2[2][0])
print(l2[2][1])
print(l2[2][2])
print(l2[2][3])
print(l2[2][4])
print(l2[2][5])

p
r
a
k
a
s


In [125]:
l

[True, 5.3, 20, 30, 34, 40, 50, 60, 100]

In [126]:
for i in l:
    print(i)

True
5.3
20
30
34
40
50
60
100


In [127]:
for i in enumerate(l):
    print(i)

(0, True)
(1, 5.3)
(2, 20)
(3, 30)
(4, 34)
(5, 40)
(6, 50)
(7, 60)
(8, 100)


In [128]:
l1

[100, 60, 50, 40, 30, 25, 20, 10]

In [129]:
all(l1)

True

In [130]:
any(l1)

True

In [131]:
l1.append(0)

In [132]:
l1

[100, 60, 50, 40, 30, 25, 20, 10, 0]

In [133]:
all(l1)

False

In [134]:
any(l1)

True

In [135]:
l4 = []

In [136]:
all(l4)

True

In [137]:
any(l4)

False

# 14th (Tuple)

In [2]:
t = () 
t

()

In [3]:
type(t)

tuple

In [4]:
t1 = (10, 20, 30)

In [5]:
t1 

(10, 20, 30)

In [6]:
t2 = (10, 2.3, 'nit', True, 1+2j)
t2

(10, 2.3, 'nit', True, (1+2j))

In [7]:
print(t)
print(t1)
print(t2)

()
(10, 20, 30)
(10, 2.3, 'nit', True, (1+2j))


In [8]:
t1

(10, 20, 30)

In [9]:
t1.count(10) 

1

In [10]:
t1

(10, 20, 30)

In [11]:
t1.index(20) 

1

In [12]:
t1

(10, 20, 30)

In [13]:
t1.append(10) 

AttributeError: 'tuple' object has no attribute 'append'

In [14]:
t1

(10, 20, 30)

In [15]:
t1[0] 

10

In [16]:
t1[0] = 100 

TypeError: 'tuple' object does not support item assignment

In [17]:
t1

(10, 20, 30)

In [18]:
t1[20] = 200 

TypeError: 'tuple' object does not support item assignment

In [19]:
icici = ('john', 123456, 'cizps') 
icici

('john', 123456, 'cizps')

In [20]:
icici [1] = 3456

TypeError: 'tuple' object does not support item assignment

In [21]:
t1

(10, 20, 30)

In [24]:
t1.remove(20)

AttributeError: 'tuple' object has no attribute 'remove'

In [25]:
t1

(10, 20, 30)

In [27]:
t3 = t1 * 3 

In [28]:
t3

(10, 20, 30, 10, 20, 30, 10, 20, 30)

# set () 

In [29]:
s = {} 
s

{}

In [30]:
type(s)

dict

In [31]:
s1 = {100, 4, 10, 3, 90, 20, 50} 
s1 

{3, 4, 10, 20, 50, 90, 100}

In [33]:
type(s1)

set

In [34]:
s2 = {3, 1+2j, True, 3.4}
s2

{(1+2j), 3, 3.4, True}

In [35]:
print(s)
print(s1)
print(s2)

{}
{50, 3, 100, 4, 20, 90, 10}
{3, True, 3.4, (1+2j)}


In [36]:
print(type(s))
print(type(s1))
print(type(s2))

<class 'dict'>
<class 'set'>
<class 'set'>


In [37]:
s1

{3, 4, 10, 20, 50, 90, 100}

In [38]:
s1.add(25)
s1

{3, 4, 10, 20, 25, 50, 90, 100}

In [39]:
s1.add(200, 300)

TypeError: set.add() takes exactly one argument (2 given)

In [40]:
s3 

NameError: name 's3' is not defined

In [41]:
s3 = s1.copy()

In [42]:
s3

{3, 4, 10, 20, 25, 50, 90, 100}

In [44]:
print(s1)
print(s2)
print(s3)

{50, 3, 100, 4, 20, 90, 25, 10}
{3, True, 3.4, (1+2j)}
{3, 100, 4, 10, 50, 20, 25, 90}


In [45]:
s3.clear() 

In [46]:
print(s1)
print(s2)
print(s3)

{50, 3, 100, 4, 20, 90, 25, 10}
{3, True, 3.4, (1+2j)}
set()


In [48]:
s1

{3, 4, 10, 20, 25, 50, 90, 100}

In [49]:
s1[0] 

TypeError: 'set' object is not subscriptable

In [50]:
s1

{3, 4, 10, 20, 25, 50, 90, 100}

In [51]:
s1[:]

TypeError: 'set' object is not subscriptable

In [52]:
s1

{3, 4, 10, 20, 25, 50, 90, 100}

In [53]:
s1.pop() 

50

In [54]:
s1.pop(2) 

TypeError: set.pop() takes no arguments (1 given)

In [55]:
s1

{3, 4, 10, 20, 25, 90, 100}

In [56]:
s1.discard(1000) 

In [57]:
s1.remove(1000) 

KeyError: 1000

In [58]:
s1.discard(4)
s1

{3, 10, 20, 25, 90, 100}

In [59]:
s1

{3, 10, 20, 25, 90, 100}

In [60]:
s1.add(10)

In [61]:
s1

{3, 10, 20, 25, 90, 100}

# 15th -- set operation

In [62]:
a = {1,2,3,4,5}
b = {4,5,6,7,8}
c = {8,9,10}

In [63]:
a.union(b)

{1, 2, 3, 4, 5, 6, 7, 8}

In [64]:
a.union(b,c) 

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [65]:
b.union(a,c)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [66]:
print(a)
print(b)
print(c)

{1, 2, 3, 4, 5}
{4, 5, 6, 7, 8}
{8, 9, 10}


In [67]:
a | b 

{1, 2, 3, 4, 5, 6, 7, 8}

In [68]:
a | b | c

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [69]:
c | a | b

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [70]:
print(a)
print(b)
print(c)

{1, 2, 3, 4, 5}
{4, 5, 6, 7, 8}
{8, 9, 10}


In [71]:
a.intersection(b)

{4, 5}

In [72]:
a.intersection(c)

set()

In [73]:
b.intersection(c)

{8}

In [74]:
c.intersection(b)

{8}

In [75]:
a & b # intersection

{4, 5}

In [77]:
print(a)
print(b)
print(c)

{1, 2, 3, 4, 5}
{4, 5, 6, 7, 8}
{8, 9, 10}


In [78]:
a & b & c 

set()

In [ ]:
# difference 

In [79]:
a.difference(b)

{1, 2, 3}

In [80]:
b.difference(a)

{6, 7, 8}

In [81]:
a.symmetric_difference(b)

{1, 2, 3, 6, 7, 8}

In [82]:
print(a)
print(b)
print(c)

{1, 2, 3, 4, 5}
{4, 5, 6, 7, 8}
{8, 9, 10}


In [83]:
b^c

{4, 5, 6, 7, 9, 10}

In [84]:
a^b^c

{1, 2, 3, 6, 7, 9, 10}

In [85]:
print(a)
print(b)
print(c)

{1, 2, 3, 4, 5}
{4, 5, 6, 7, 8}
{8, 9, 10}


In [86]:
a1 = {1,2,3,4,5}
b1 = {4,5,6,7,8}
c1 = {8,9,10}

In [87]:
a1.intersection_update(b1) 

In [88]:
a1

{4, 5}

In [89]:
print(a1)
print(b1)
print(c1)

{4, 5}
{4, 5, 6, 7, 8}
{8, 9, 10}


In [90]:
b1.difference_update(b1) 

In [91]:
print(a1)
print(b1)
print(c1)

{4, 5}
set()
{8, 9, 10}


In [92]:
a1 = {1,2,3,4,5}
b1 = {4,5,6,7,8}
c1 = {8,9,10}

In [93]:
b1.difference_update(c1)

In [95]:
print(a1)
print(b1)
print(c1)

{1, 2, 3, 4, 5}
{4, 5, 6, 7}
{8, 9, 10}


In [96]:
b1.symmetric_difference_update(c1)

In [97]:
b1

{4, 5, 6, 7, 8, 9, 10}

In [98]:
print(a1)
print(b1)
print(c1)

{1, 2, 3, 4, 5}
{4, 5, 6, 7, 8, 9, 10}
{8, 9, 10}


In [99]:
a1.update(b1)

In [100]:
a1

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [101]:
# superset , subset, disjoint

In [103]:
a2 = {1,2,3,4,5,6,7,8,9}
b2 = {3,4,5,6,7,8} 
c2 = {10,20,30,40}

In [104]:
a2.issuperset(b2)

True

In [105]:
a2.isdisjoint(c2)

True

In [107]:
a2.isdisjoint(b2) 

False

In [ ]:
a2 = {1,2,3,4,5,6,7,8,9}
b2 = {3,4,5,6,7,8} 
c2 = {10,20,30,40} 

In [108]:
b2.issubset(a2)

True

In [109]:
b2.isdisjoint(c2)

True

In [110]:
a3 = {1, 2, 3, 4, 5, 6, 7, 8, 9}
b3 = {15,25, 35,45} 
c3 = {10,20,30,40} 

In [111]:
a3.issuperset(b3) 

False

In [112]:
a3.isdisjoint(b3)

True

In [113]:
b3.issubset(a3)

False

In [ ]:
a3.

# SET DATASTRUCTURE COMPLETED 

In [114]:
my_tuple = (1)
my_tuple

1

In [115]:
type(my_tuple)

int

my_tuple_1 = (1,)
my_tuple_1

In [117]:
type(my_tuple_1)

tuple

# range()

In [120]:
range(5) 

range(0, 5)

In [121]:
for i in range(5):
    print(i)

0
1
2
3
4


In [122]:
list(range(5))

[0, 1, 2, 3, 4]

In [123]:
range(10, 20)

range(10, 20)

In [124]:
list(range(10,20))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [125]:
list(range(10,50,5))

[10, 15, 20, 25, 30, 35, 40, 45]

In [126]:
list(range(10,50,5,3))

TypeError: range expected at most 3 arguments, got 4

# dictinary

In [127]:
d = {1: 'one', 2: 'two', 3 :'three'}
d

{1: 'one', 2: 'two', 3: 'three'}

In [128]:
type(d)

dict

In [129]:
d

{1: 'one', 2: 'two', 3: 'three'}

In [131]:
d[1]

'one'

In [132]:
d[2]

'two'

In [133]:
d[3]

'three'

In [134]:
d

{1: 'one', 2: 'two', 3: 'three'}

In [136]:
d.items() 

dict_items([(1, 'one'), (2, 'two'), (3, 'three')])

In [137]:
d

{1: 'one', 2: 'two', 3: 'three'}

In [138]:
d[4] = 'four'
d

{1: 'one', 2: 'two', 3: 'three', 4: 'four'}

In [139]:
d[5] = [1,2,3]

In [140]:
d

{1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: [1, 2, 3]}

In [141]:
d[2+3j] = True

In [142]:
d

{1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: [1, 2, 3], (2+3j): True}

In [143]:
keys = {'a' , 'b' , 'c' , 'd'}
value = [10,20,30]

mydict3 = dict.fromkeys(keys , value) # Create a dictionary from a sequence of
mydict3

{'b': [10, 20, 30], 'd': [10, 20, 30], 'a': [10, 20, 30], 'c': [10, 20, 30]}

In [144]:
value.append(40)
mydict3

{'b': [10, 20, 30, 40],
 'd': [10, 20, 30, 40],
 'a': [10, 20, 30, 40],
 'c': [10, 20, 30, 40]}

In [145]:
s3 = {10,20,30,40} 
s3.add(70)
s3

{10, 20, 30, 40, 70}

In [146]:
fs = frozenset(s3)
fs

frozenset({10, 20, 30, 40, 70})

In [147]:
type(fs)

frozenset

In [148]:
fs.add(100)

AttributeError: 'frozenset' object has no attribute 'add'

In [149]:
fs.remove(10)

AttributeError: 'frozenset' object has no attribute 'remove'

In [150]:
fs

frozenset({10, 20, 30, 40, 70})

In [151]:
fs.pop()

AttributeError: 'frozenset' object has no attribute 'pop'

# print()

In [153]:
num1=20
num2=30
add=num1+num2
print(add)

50


In [154]:
num1=20
num2=30

add=num1+num2

print('The addition of',num1,'and',num2,'is=',add)

The addition of 20 and 30 is= 50


In [155]:
num1=20
num2=30
num3=50

add=num1+num2+num3

print('The addition of',num1,'and',num2,'and', num3,'is=',add)

The addition of 20 and 30 and 50 is= 100


In [156]:
name='Python'
age=20
city='hyd'

print('My name is',name,'and i am',age,'years old form',city)

My name is Python and i am 20 years old form hyd


In [1]:
num1=20
num2=30

add=num1+num2

print('The addition of {} and {} is= {}'.format(num1,num2,add))

The addition of 20 and 30 is= 50


In [2]:
num1=20
num2=30
num3=40

add=num1+num2 + num3

print('The addition of {} and {} and {} is= {}'.format(num1,num2,num3,add))

The addition of 20 and 30 and 40 is= 90


In [3]:
num1 = 30
num2 = 40 
add=num1+num2
print(f'The addition of {num1} and {num2} is= {add}') # alwase prefer this

The addition of 30 and 40 is= 70


In [4]:
print('hello team') # 1st statement
print('good moorning') #2nd statment 

hello team
good moorning


In [6]:
print('hello team', end = ' ') # 1st statement
print('good moorning') #2nd statment 

hello team good moorning


In [7]:
print('hello team', end = ' ### ') # 1st statement
print('good moorning') #2nd statment 

hello team ### good moorning


# Numpy crash course

In [9]:
import numpy as np

In [10]:
np.__version__ 

'2.3.5'

In [11]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [12]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [13]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(10,50,5) 

array([10, 15, 20, 25, 30, 35, 40, 45])

In [17]:
np.arange(10,50,5,1) 

TypeError: Cannot interpret '1' as a data type

In [18]:
np.arange(20, 10) 

array([], dtype=int64)

In [19]:
np.arange(-20, 10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [24]:
np.zeros(3, dtype=float)  #1d array (parameter tunning) 

array([0., 0., 0.])

In [23]:
np.zeros(3, dtype=int)  #1d array (hyperparameer tunning) 

array([0, 0, 0])

In [26]:
np.zeros([2,2]) #2d array

array([[0., 0.],
       [0., 0.]])

In [27]:
np.zeros([10,10], dtype=int) #nd array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [28]:
np.ones(4) 

array([1., 1., 1., 1.])

In [30]:
np.ones(4, dtype=int) 

array([1, 1, 1, 1])

In [31]:
np.two(3)

AttributeError: module 'numpy' has no attribute 'two'

In [32]:
np.rand(3)

AttributeError: module 'numpy' has no attribute 'rand'

In [37]:
np.random.rand(3)

array([0.2312211 , 0.88269695, 0.84984068])

In [46]:
np.random.rand(3,4) 

array([[0.37344988, 0.58088127, 0.30453977, 0.225893  ],
       [0.67480596, 0.87885848, 0.3794117 , 0.93929663],
       [0.00820513, 0.37416533, 0.32871725, 0.21236874]])

In [54]:
np.random.randint(3)

0

In [57]:
np.random.randint(10,20)

13

In [58]:
np.random.randint(1,10,4) 

array([9, 6, 7, 7], dtype=int32)

In [63]:
print(np.random.randint(1,10,4)) 

[7 8 7 9]


In [67]:
m = np.random.randint(1,10,(4,6))
print(m)

[[2 6 9 5 9 4]
 [9 6 2 8 1 8]
 [1 4 1 2 3 6]
 [6 1 8 6 5 9]]


In [68]:
# indexiing & slicing in array 

In [70]:
print(m)

[[2 6 9 5 9 4]
 [9 6 2 8 1 8]
 [1 4 1 2 3 6]
 [6 1 8 6 5 9]]


In [71]:
m[0] 

array([2, 6, 9, 5, 9, 4], dtype=int32)

In [73]:
m[0] = [4,5,6,7,8,9]

In [74]:
m

array([[4, 5, 6, 7, 8, 9],
       [9, 6, 2, 8, 1, 8],
       [1, 4, 1, 2, 3, 6],
       [6, 1, 8, 6, 5, 9]], dtype=int32)

In [78]:
m[2]

array([1, 4, 1, 2, 3, 6], dtype=int32)

In [79]:
m[-3]

array([9, 6, 2, 8, 1, 8], dtype=int32)

In [80]:
m

array([[4, 5, 6, 7, 8, 9],
       [9, 6, 2, 8, 1, 8],
       [1, 4, 1, 2, 3, 6],
       [6, 1, 8, 6, 5, 9]], dtype=int32)

In [82]:
print(m[0,4])

8


In [83]:
m

array([[4, 5, 6, 7, 8, 9],
       [9, 6, 2, 8, 1, 8],
       [1, 4, 1, 2, 3, 6],
       [6, 1, 8, 6, 5, 9]], dtype=int32)

In [84]:
print(m[-2, -3])

2
